import { ThemeConfig, ThemeId, WeddingData, RSVPRecord, MarketplaceOrder, MusicTrack, EventBlockConfig, EventCategoryPreset, RSVPSurveyConfig } from '../types/invitation';

export const DEFAULT_RSVP_SURVEY: RSVPSurveyConfig = {
  allowPlusOnes: true,
  maxPlusOnes: 3,
  askMealPreference: true,
  mealOptions: [
    'Charred Prime Beef Tenderloin (Truffle Mash & Port Jus)',
    'Crispy Skin King Salmon (Saffron Risotto & Citrus Emulsion)',
    'Wild Mushroom & Truffle Risotto (Vegetarian / GF)',
    'Roasted Butternut Squash & Quinoa (Vegan)',
  ],
  askDietaryRestrictions: true,
  dietaryOptions: [
    'Gluten-Free',
    'Vegetarian',
    'Vegan',
    'Dairy-Free',
    'Nut Allergy',
    'Shellfish Allergy',
    'Kosher / Halal',
  ],
  askSongRequest: true,
  songRequestPrompt: 'A song that will get you on the dance floor!',
  askPersonalMessage: true,
  customQuestions: [
    {
      id: 'q-1',
      question: 'Will you be taking the complimentary guest shuttle?',
      placeholder: 'Yes, from Oneroa Wharf / No, driving directly',
      required: false,
    },
  ],
};

export const THEME_PRESETS: Record<ThemeId, ThemeConfig> = {
  'olive-burgundy': {
    id: 'olive-burgundy',
    name: 'Olive & Burgundy Romance',
    subtitle: 'Classic vineyard botanical with deep burgundy wax seal and swan lake art',
    envelopeColor: '#535e3b',
    envelopeFlapColor: '#434d2f',
    waxSealBg: '#671928',
    waxSealBorder: '#8a2438',
    waxSealColor: '#f7e3c3',
    waxSealText: 'L&S',
    cardBg: '#2d3822',
    cardBorder: '#485737',
    cardTextPrimary: '#fbf8f2',
    cardTextSecondary: '#c8d4b8',
    cardAccentColor: '#d6a354',
    badgeBg: '#591421',
    badgeText: '#fcebe6',
    bgGradient: 'from-[#171c13] via-[#242c1e] to-[#12160f]',
    illustrationUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Claire de Lune (Acoustic Wedding Harp)',
  },
  'champagne-noir': {
    id: 'champagne-noir',
    name: 'Champagne & Noir Luxury',
    subtitle: 'Old money editorial chic with obsidian paper and shimmering champagne foil',
    envelopeColor: '#1c1c1c',
    envelopeFlapColor: '#141414',
    waxSealBg: '#b8964e',
    waxSealBorder: '#d4af37',
    waxSealColor: '#1c1c1c',
    waxSealText: 'V&A',
    cardBg: '#121212',
    cardBorder: '#383838',
    cardTextPrimary: '#fefefe',
    cardTextSecondary: '#d8caa7',
    cardAccentColor: '#d4af37',
    badgeBg: '#262626',
    badgeText: '#f3e8c9',
    bgGradient: 'from-[#0d0d0d] via-[#1a1a1a] to-[#0a0a0a]',
    illustrationUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'Canon in D (Strings & Piano)',
  },
  'tuscan-terracotta': {
    id: 'tuscan-terracotta',
    name: 'Tuscan Sun Terracotta',
    subtitle: 'Warm Italian countryside villa with burnt sienna, olive oil and travertine',
    envelopeColor: '#93543d',
    envelopeFlapColor: '#7a422e',
    waxSealBg: '#445136',
    waxSealBorder: '#5d6f4b',
    waxSealColor: '#faede3',
    waxSealText: 'M&E',
    cardBg: '#faf5ef',
    cardBorder: '#e4d5c4',
    cardTextPrimary: '#3f2b23',
    cardTextSecondary: '#7a5e51',
    cardAccentColor: '#93543d',
    badgeBg: '#80412b',
    badgeText: '#fff3eb',
    bgGradient: 'from-[#2e1d17] via-[#482e24] to-[#20130d]',
    illustrationUrl: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Italian Villa Romance (Acoustic Guitar)',
  },
  'dusty-rose': {
    id: 'dusty-rose',
    name: 'Dusty Rose & French Mauve',
    subtitle: 'Chateau garden romance with soft heirloom roses and delicate calligraphy',
    envelopeColor: '#7b5a63',
    envelopeFlapColor: '#63444c',
    waxSealBg: '#966e77',
    waxSealBorder: '#b38a94',
    waxSealColor: '#fff5f7',
    waxSealText: 'C&H',
    cardBg: '#fffbfb',
    cardBorder: '#eedbdc',
    cardTextPrimary: '#3e2a2f',
    cardTextSecondary: '#8a6b73',
    cardAccentColor: '#b06f80',
    badgeBg: '#6b4851',
    badgeText: '#fff0f3',
    bgGradient: 'from-[#26171b] via-[#3a252b] to-[#1c1114]',
    illustrationUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'A Thousand Years (Violin Duo)',
  },
  'botanical-emerald': {
    id: 'botanical-emerald',
    name: 'Imperial Emerald & Gold',
    subtitle: 'Lush conservatory greenery, gold leaf typography, and crisp linen cards',
    envelopeColor: '#1c4436',
    envelopeFlapColor: '#133328',
    waxSealBg: '#c29b38',
    waxSealBorder: '#dfb755',
    waxSealColor: '#133328',
    waxSealText: 'G&T',
    cardBg: '#fbfcf9',
    cardBorder: '#d6e2db',
    cardTextPrimary: '#163127',
    cardTextSecondary: '#476558',
    cardAccentColor: '#b8860b',
    badgeBg: '#1b4436',
    badgeText: '#f0fdf4',
    bgGradient: 'from-[#081813] via-[#0f2a20] to-[#05100c]',
    illustrationUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Bridal Chorus (Cello & Harp)',
  },
};

export const INITIAL_WEDDING_DATA: WeddingData = {
  id: 'wed-001',
  slug: 'liam-and-scarlett',
  coupleName1: 'Liam',
  coupleName2: 'Scarlett',
  coupleInitials: 'L&S',
  subtitleIntro: 'INTRODUCING',
  headline: 'PLEASE JOIN US FOR THE WEDDING OF',
  weddingDate: '2027-08-11',
  weddingTime: '3:45 PM',
  venueName: 'Cable Bay Vineyard',
  venueAddress: '12 Nick Johnstone Drive, Oneroa',
  cityState: 'Waiheke Island, New Zealand',
  mapsUrl: 'https://maps.google.com/?q=Cable+Bay+Vineyard+Waiheke+Island',
  rsvpDeadline: 'June 15, 2027',
  themeId: 'olive-burgundy',
  rsvpSurvey: DEFAULT_RSVP_SURVEY,
  transportInfo: 'On the day, return transport will be arranged from central Oneroa and the ferry wharf to Cable Bay Vineyard and back after the reception.',
  giftRegistryUrl: 'https://www.zola.com/registry',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
  timeline: [
    {
      id: 't-1',
      time: '3:45 PM',
      title: 'Guest Arrival & Champagne Welcome',
      description: 'Guests arrive at the glasshouse terrace for sparkling wine and live acoustic harp.',
      icon: 'cocktail',
    },
    {
      id: 't-2',
      time: '4:15 PM',
      title: 'The Wedding Ceremony',
      description: 'Exchange of vows overlooking the panoramic bay vineyards.',
      icon: 'ceremony',
    },
    {
      id: 't-3',
      time: '5:00 PM',
      title: 'Cocktails & Canapes',
      description: 'Sunset drinks, gourmet oyster bar, and lawn games in the olive grove.',
      icon: 'cocktail',
    },
    {
      id: 't-4',
      time: '7:00 PM',
      title: 'Seated Dinner & Speeches',
      description: 'Five-course farm-to-table wine pairing dinner followed by champagne toasts.',
      icon: 'toast',
    },
    {
      id: 't-5',
      time: '8:30 PM',
      title: 'Cutting the Wedding Cake',
      description: 'Sweet moments, espresso bar, and artisan dessert table.',
      icon: 'cake',
    },
    {
      id: 't-6',
      time: '9:00 PM - Midnight',
      title: 'First Dance & Dancing Time',
      description: 'Live 7-piece band and open cocktail bar to dance the night away.',
      icon: 'dancing',
    },
  ],
  hotels: [
    {
      id: 'h-1',
      name: 'Oneroa Bay Luxury Retreat',
      badge: '5 Min from Venue',
      description: 'Boutique waterfront villas with private infinity pools and coastal views.',
      bookingUrl: 'https://www.booking.com',
      discountCode: 'LIAMSCARLETT27',
      priceLevel: '$$$$',
    },
    {
      id: 'h-2',
      name: 'The Vineyard Estate Cottages',
      badge: 'On-site Partner',
      description: 'Charming rustic stone suites nestled right among the vines with breakfast included.',
      bookingUrl: 'https://www.airbnb.com',
      discountCode: 'WEDDINGGUEST',
      priceLevel: '$$$',
    },
  ],
  dressCode: {
    title: 'Dress to Impress',
    subtitle: 'Black Tie Optional / Vineyard Elegance',
    description: "We would love for you to join us celebrating in style in formal vineyard attire. For the ladies, floor-length or elevated midi dresses in rich tones. For gentlemen, dark suits or classic tuxedos.",
    swatches: [
      { name: 'Olive Green', hex: '#4e5b30' },
      { name: 'Deep Burgundy', hex: '#671928' },
      { name: 'Warm Terracotta', hex: '#93543d' },
      { name: 'Champagne Gold', hex: '#d4af37' },
      { name: 'Black Tie Noir', hex: '#1c1c1c' },
    ],
  },
  menu: [
    {
      id: 'm-1',
      course: 'Canapés & Starters',
      title: 'Seared King Salmon & Caviar',
      description: 'Pan-seared Ora King Salmon, dill emulsion, crisp capers & Oscietra caviar.',
      dietaryTags: ['Gluten-Free']
    },
    {
      id: 'm-2',
      course: 'Canapés & Starters',
      title: 'Truffle & Wild Porcini Arancini',
      description: 'Crispy carnaroli risotto pearls, aged Parmesan fonduta & black summer truffle.',
      dietaryTags: ['Vegetarian']
    },
    {
      id: 'm-3',
      course: 'Main Entrée',
      title: 'Prime Angus Beef Tenderloin',
      description: 'Charred broccolini, confit garlic potato purée, and 48-hour bone marrow jus.',
      dietaryTags: ['Gluten-Free']
    },
    {
      id: 'm-4',
      course: 'Main Entrée',
      title: 'Heirloom Roasted Butternut Risotto',
      description: 'Acquerello rice, crispy sage, toasted pine nuts, and vegan Parmesan crisp.',
      dietaryTags: ['Vegan', 'Gluten-Free']
    },
    {
      id: 'm-5',
      course: 'Dessert & Cake',
      title: 'Madagascan Vanilla & Gold Leaf Cake',
      description: 'Layered chiffon sponge, passionfruit curd, and champagne buttercream.',
      dietaryTags: ['Vegetarian']
    },
    {
      id: 'm-6',
      course: 'Signature Cocktails',
      title: 'The Golden Vow (French 75)',
      description: 'Botanical artisanal gin, lemon essence, raw sugar, topped with vintage champagne.',
      dietaryTags: []
    }
  ],
  storyTitle: 'From Paris to Forever',
  storyText: 'We met on a rainy autumn evening in Montmartre, Paris. Five years, countless adventures across 14 countries, and a sunset proposal on the Amalfi cliffs later — we are beyond ecstatic to begin this next chapter with our dearest family and friends.',
  faqs: [
    {
      id: 'f-1',
      question: 'What is the dress code?',
      answer: 'Our dress code is Black Tie Optional / Formal Vineyard Elegance. Dark suits, tuxedos, and floor-length or elevated midi gowns are welcome.'
    },
    {
      id: 'f-2',
      question: 'Are children invited?',
      answer: 'While we adore your little ones, our ceremony and reception are strictly an adult-only celebration.'
    },
    {
      id: 'f-3',
      question: 'Is there parking available?',
      answer: 'Yes, complimentary valet parking is provided upon arrival at the venue gates.'
    },
    {
      id: 'f-4',
      question: 'Can I bring a guest / Plus One?',
      answer: 'Due to venue intimacy, seats are reserved exclusively for the guests named on your invitation.'
    }
  ],
  photos: [
    {
      id: 'p-1',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
      caption: 'Where it all started - Paris, 2021',
      dateTag: 'October 2021',
    },
    {
      id: 'p-2',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
      caption: 'She said YES on the Amalfi Coast!',
      dateTag: 'September 2024',
    },
    {
      id: 'p-3',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
      caption: 'Counting down the days with you',
      dateTag: 'Summer 2026',
    },
  ],
};

export const INITIAL_RSVPS: RSVPRecord[] = [
  {
    id: 'rsvp-1',
    weddingId: 'wed-001',
    guestName: 'Eleanor Vance',
    guestEmail: 'eleanor.vance@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Julian Vance'],
    mealChoice: 'Charred Prime Beef Tenderloin',
    dietaryNotes: 'Gluten-free for Eleanor',
    songRequest: 'At Last - Etta James',
    personalMessage: 'So incredibly thrilled for you both! Can not wait to celebrate under the stars!',
    submittedAt: '2026-08-14T10:30:00Z',
  },
  {
    id: 'rsvp-2',
    weddingId: 'wed-001',
    guestName: 'Marcus Sterling',
    guestEmail: 'marcus.s@example.com',
    attendance: 'attending',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'Crispy Skin King Salmon',
    dietaryNotes: 'None',
    songRequest: 'September - Earth, Wind & Fire',
    personalMessage: 'Ready for the greatest party of 2027!',
    submittedAt: '2026-08-15T14:12:00Z',
  },
  {
    id: 'rsvp-3',
    weddingId: 'wed-001',
    guestName: 'Sophia Montgomery',
    guestEmail: 'sophia.m@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Lucas Montgomery'],
    mealChoice: 'Wild Mushroom & Truffle Risotto (V)',
    dietaryNotes: 'Vegetarian',
    songRequest: 'Lover - Taylor Swift',
    personalMessage: 'Liam & Scarlett, you two are pure magic. See you on Waiheke!',
    submittedAt: '2026-08-16T09:45:00Z',
  },
  {
    id: 'rsvp-4',
    weddingId: 'wed-001',
    guestName: 'Arthur Pendelton',
    guestEmail: 'arthur.p@example.com',
    attendance: 'declined',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'N/A',
    dietaryNotes: '',
    personalMessage: 'Sending all our love from London! Sadly cannot make the flight but will be toasting with champagne!',
    submittedAt: '2026-08-16T16:20:00Z',
  },
];

export const INITIAL_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ord-8891',
    claimCode: 'ETSY-OLIVE-9482',
    platform: 'Etsy',
    buyerName: 'Charlotte Miller',
    buyerEmail: 'charlotte.m@gmail.com',
    themeSelected: 'olive-burgundy',
    orderStatus: 'claimed',
    createdAt: '2026-09-08 19:30',
    claimedAt: '2026-09-08 20:15',
  },
  {
    id: 'ord-8892',
    claimCode: 'GUM-CHAMP-1029',
    platform: 'Gumroad',
    buyerName: 'Benjamin Hayes',
    buyerEmail: 'ben.hayes@outlook.com',
    themeSelected: 'champagne-noir',
    orderStatus: 'generated',
    createdAt: '2026-09-09 08:45',
  },
  {
    id: 'ord-8893',
    claimCode: 'ETSY-TUSCAN-7734',
    platform: 'Etsy',
    buyerName: 'Isabella Rossi',
    buyerEmail: 'isabella.r@gmail.com',
    themeSelected: 'tuscan-terracotta',
    orderStatus: 'published',
    createdAt: '2026-09-07 14:10',
    claimedAt: '2026-09-07 15:00',
  }
];

export const CURATED_MUSIC_OPTIONS: MusicTrack[] = [
  {
    id: 'piano-romance',
    title: 'Cinematic Piano Romance',
    artist: 'Eternelle Studio',
    genre: 'Solo Piano',
    duration: '2:45',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    description: 'Heartfelt, emotional solo piano ballad with classic romantic chords.',
  },
  {
    id: 'acoustic-vows',
    title: 'Acoustic Sunset Guitar',
    artist: 'Acoustic Serenade',
    genre: 'Fingerstyle Guitar',
    duration: '3:12',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=acoustic-guitar-wedding-18088.mp3',
    description: 'Warm fingerpicked acoustic guitar suited for outdoor, rustic & coastal weddings.',
  },
  {
    id: 'harp-celestial',
    title: 'Celestial Wedding Harp',
    artist: 'St. Claire Ensemble',
    genre: 'Cathedral Harp',
    duration: '2:15',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=wedding-harp-10548.mp3',
    description: 'Ethereal angelic harp arpeggios providing pure fairy-tale luxury.',
  },
  {
    id: 'royal-strings',
    title: 'Bridgerton String Quartet',
    artist: 'Mayfair Chamber Players',
    genre: 'String Quartet',
    duration: '3:30',
    url: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=cinematic-strings-wedding-6430.mp3',
    description: 'Opulent violin and cello arrangement for grand ballroom ceremonies.',
  },
  {
    id: 'lofi-twilight',
    title: 'Twilight Lo-Fi Vows',
    artist: 'Sunset Chords',
    genre: 'Modern Ambient Lo-Fi',
    duration: '2:50',
    url: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f77c30.mp3?filename=lofi-romance-124018.mp3',
    description: 'Modern, chill romantic beat with soft tape-decay Rhodes piano.',
  },
];

export const DEFAULT_EVENT_BLOCKS: Record<string, EventBlockConfig[]> = {
  wedding: [
    { id: 'story', title: 'Our Love Story', icon: '❤️', enabled: true },
    { id: 'schedule', title: 'Order of Events', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Food & Drinks Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Photo Gallery', icon: '📸', enabled: true },
    { id: 'attire', title: 'Dress Code & Palette', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: true },
    { id: 'faqs', title: 'Guest Q&A / FAQs', icon: '❓', enabled: true },
  ],
  engagement: [
    { id: 'story', title: 'The Proposal Story', icon: '💍', enabled: true },
    { id: 'schedule', title: 'Celebration Timeline', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Cocktails & Canapés', icon: '🍸', enabled: true },
    { id: 'gallery', title: 'Engagement Portraits', icon: '📸', enabled: true },
    { id: 'attire', title: 'Cocktail Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Party Details & FAQs', icon: '❓', enabled: true },
  ],
  birthday: [
    { id: 'story', title: 'A Chapter of Memories', icon: '✨', enabled: true },
    { id: 'schedule', title: 'Party Schedule', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Birthday Bites & Bar', icon: '🎂', enabled: true },
    { id: 'gallery', title: 'Memory Reel', icon: '📸', enabled: true },
    { id: 'attire', title: 'Party Theme & Attire', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Party Info & Wishlist', icon: '❓', enabled: true },
  ],
  anniversary: [
    { id: 'story', title: 'Years of Love Timeline', icon: '🥂', enabled: true },
    { id: 'schedule', title: 'Toast & Dinner Schedule', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Anniversary Dinner Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Journey Through the Years', icon: '📸', enabled: true },
    { id: 'attire', title: 'Attire & Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Hotel Recommendations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Guest FAQs', icon: '❓', enabled: true },
  ],
  baby_shower: [
    { id: 'story', title: 'Welcoming Our Little Blessing', icon: '🍼', enabled: true },
    { id: 'schedule', title: 'Shower Schedule & Games', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Sweets & Refreshments', icon: '🧁', enabled: true },
    { id: 'gallery', title: 'Maternity Moments', icon: '📸', enabled: true },
    { id: 'attire', title: 'Theme & Pastel Palette', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Travel & Accommodations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Registry & Diaper Raffle', icon: '🎁', enabled: true },
  ],
  gala: [
    { id: 'story', title: 'Mission & Keynote Vision', icon: '🎙️', enabled: true },
    { id: 'schedule', title: 'Gala Evening Itinerary', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Banquet & Wine Pairings', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Past Gala Highlights', icon: '📸', enabled: true },
    { id: 'attire', title: 'Black-Tie Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'VIP Accommodations & Travel', icon: '🏨', enabled: true },
    { id: 'faqs', title: 'Sponsorship & Seating FAQs', icon: '❓', enabled: true },
  ],
  custom: [
    { id: 'story', title: 'About This Celebration', icon: '✨', enabled: true },
    { id: 'schedule', title: 'Order of Events', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Food & Drinks Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Photo Highlights', icon: '📸', enabled: true },
    { id: 'attire', title: 'Attire & Theme', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Event FAQs', icon: '❓', enabled: true },
  ],
};

export const EVENT_CATEGORY_PRESETS: Record<string, EventCategoryPreset> = {
  wedding: {
    type: 'wedding',
    label: 'Wedding & Reception',
    badge: 'Couture Classic',
    icon: '💍',
    description: 'Ceremony, grand dinner, toasts, bridal party & honeymoon registry.',
    defaultHeadline: 'PLEASE JOIN US FOR THE WEDDING OF',
    defaultSubtitle: 'TOGETHER WITH THEIR FAMILIES',
    defaultStoryTitle: 'Our Love Story',
    defaultTheme: 'botanical-emerald',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.wedding,
  },
  engagement: {
    type: 'engagement',
    label: 'Engagement Party',
    badge: 'Chic Celebration',
    icon: '💎',
    description: 'Cocktail soirée, champagne toasts, and proposal celebration.',
    defaultHeadline: 'JOIN US TO CELEBRATE THE ENGAGEMENT OF',
    defaultSubtitle: 'POP THE CHAMPAGNE FOR',
    defaultStoryTitle: 'The Proposal',
    defaultTheme: 'dusty-rose',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.engagement,
  },
  birthday: {
    type: 'birthday',
    label: 'Birthday & Milestone',
    badge: 'Milestone Soirée',
    icon: '🎂',
    description: '1st, 18th, 21st, 30th, 40th, 50th and milestone birthday celebrations.',
    defaultHeadline: 'YOU ARE CORDIALLY INVITED TO CELEBRATE',
    defaultSubtitle: 'A SPECTACULAR MILESTONE',
    defaultStoryTitle: 'A Chapter of Memories',
    defaultTheme: 'champagne-noir',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.birthday,
  },
  anniversary: {
    type: 'anniversary',
    label: 'Anniversary & Vow Renewal',
    badge: 'Golden Romance',
    icon: '🥂',
    description: 'Celebrating 10, 25, 50 years of love, memories and renewed vows.',
    defaultHeadline: 'CELEBRATING 25 YEARS OF LOVE & DEVOTION',
    defaultSubtitle: 'HONOURING THE ANNIVERSARY OF',
    defaultStoryTitle: '25 Years of Beautiful Memories',
    defaultTheme: 'tuscan-terracotta',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.anniversary,
  },
  baby_shower: {
    type: 'baby_shower',
    label: 'Baby Shower & Gender Reveal',
    badge: 'Sweet Welcome',
    icon: '🍼',
    description: 'Welcoming the new arrival with registry links and sweet festivities.',
    defaultHeadline: 'JOIN US IN CELEBRATING THE ARRIVAL OF',
    defaultSubtitle: 'A SWEET LITTLE BLESSING',
    defaultStoryTitle: 'Our Growing Family',
    defaultTheme: 'dusty-rose',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.baby_shower,
  },
  gala: {
    type: 'gala',
    label: 'Gala, Soirée & Charity Dinner',
    badge: 'Black-Tie Editorial',
    icon: '🍸',
    description: 'Formal charity galas, keynote banquets, and annual celebrations.',
    defaultHeadline: 'REQUESTS THE PLEASURE OF YOUR COMPANY AT',
    defaultSubtitle: 'ANNUAL CHARITY SOIREE',
    defaultStoryTitle: 'Our Mission & Vision',
    defaultTheme: 'champagne-noir',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.gala,
  },
  custom: {
    type: 'custom',
    label: 'Custom Milestone',
    badge: 'Bespoke Atelier',
    icon: '✨',
    description: 'Design your own custom celebration with bespoke titles and sections.',
    defaultHeadline: 'CORDIALLY INVITES YOU TO CELEBRATE',
    defaultSubtitle: 'AN EXCLUSIVE GATHERING',
    defaultStoryTitle: 'About This Event',
    defaultTheme: 'botanical-emerald',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.custom,
  },
};

