import { ThemeConfig, ThemeId, WeddingData, RSVPRecord, MarketplaceOrder, MusicTrack, EventBlockConfig, EventCategoryPreset, RSVPSurveyConfig } from '../types/invitation';

export const DEFAULT_RSVP_SURVEY: RSVPSurveyConfig = {
  allowPlusOnes: true,
  maxPlusOnes: 3,
  askMealPreference: true,
  mealOptions: [
    'Charred Prime Beef Tenderloin (Truffle Mash & Port Jus)',
    'Crispy Skin King Salmon (Saffron Risotto & Citrus Emulsion)',
    'Wild Mushroom & Truffle Risotto (Vegetarian / GF)',
    'Roasted Butternut Squash & Quinoa (Vegan)',
  ],
  askDietaryRestrictions: true,
  dietaryOptions: [
    'Gluten-Free',
    'Vegetarian',
    'Vegan',
    'Dairy-Free',
    'Nut Allergy',
    'Shellfish Allergy',
    'Kosher / Halal',
  ],
  askSongRequest: true,
  songRequestPrompt: 'A song that will get you on the dance floor!',
  askPersonalMessage: true,
  customQuestions: [
    {
      id: 'q-1',
      question: 'Will you be taking the complimentary guest shuttle?',
      placeholder: 'Yes, from Oneroa Wharf / No, driving directly',
      required: false,
    },
  ],
};

export const THEME_PRESETS: Record<ThemeId, ThemeConfig> = {
  'olive-burgundy': {
    id: 'olive-burgundy',
    name: 'Olive & Burgundy Romance',
    subtitle: 'Classic vineyard botanical with deep burgundy wax seal and swan lake art',
    envelopeColor: '#535e3b',
    envelopeFlapColor: '#434d2f',
    waxSealBg: '#671928',
    waxSealBorder: '#8a2438',
    waxSealColor: '#f7e3c3',
    waxSealText: 'L&S',
    cardBg: '#2d3822',
    cardBorder: '#485737',
    cardTextPrimary: '#fbf8f2',
    cardTextSecondary: '#c8d4b8',
    cardAccentColor: '#d6a354',
    badgeBg: '#591421',
    badgeText: '#fcebe6',
    bgGradient: 'from-[#171c13] via-[#242c1e] to-[#12160f]',
    illustrationUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Claire de Lune (Acoustic Wedding Harp)',
  },
  'champagne-noir': {
    id: 'champagne-noir',
    name: 'Champagne & Noir Luxury',
    subtitle: 'Old money editorial chic with obsidian paper and shimmering champagne foil',
    envelopeColor: '#1c1c1c',
    envelopeFlapColor: '#141414',
    waxSealBg: '#b8964e',
    waxSealBorder: '#d4af37',
    waxSealColor: '#1c1c1c',
    waxSealText: 'V&A',
    cardBg: '#121212',
    cardBorder: '#383838',
    cardTextPrimary: '#fefefe',
    cardTextSecondary: '#d8caa7',
    cardAccentColor: '#d4af37',
    badgeBg: '#262626',
    badgeText: '#f3e8c9',
    bgGradient: 'from-[#0d0d0d] via-[#1a1a1a] to-[#0a0a0a]',
    illustrationUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'Canon in D (Strings & Piano)',
  },
  'tuscan-terracotta': {
    id: 'tuscan-terracotta',
    name: 'Tuscan Sun Terracotta',
    subtitle: 'Warm Italian countryside villa with burnt sienna, olive oil and travertine',
    envelopeColor: '#93543d',
    envelopeFlapColor: '#7a422e',
    waxSealBg: '#445136',
    waxSealBorder: '#5d6f4b',
    waxSealColor: '#faede3',
    waxSealText: 'M&E',
    cardBg: '#faf5ef',
    cardBorder: '#e4d5c4',
    cardTextPrimary: '#3f2b23',
    cardTextSecondary: '#7a5e51',
    cardAccentColor: '#93543d',
    badgeBg: '#80412b',
    badgeText: '#fff3eb',
    bgGradient: 'from-[#2e1d17] via-[#482e24] to-[#20130d]',
    illustrationUrl: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Italian Villa Romance (Acoustic Guitar)',
  },
  'dusty-rose': {
    id: 'dusty-rose',
    name: 'Dusty Rose & French Mauve',
    subtitle: 'Chateau garden romance with soft heirloom roses and delicate calligraphy',
    envelopeColor: '#7b5a63',
    envelopeFlapColor: '#63444c',
    waxSealBg: '#966e77',
    waxSealBorder: '#b38a94',
    waxSealColor: '#fff5f7',
    waxSealText: 'C&H',
    cardBg: '#fffbfb',
    cardBorder: '#eedbdc',
    cardTextPrimary: '#3e2a2f',
    cardTextSecondary: '#8a6b73',
    cardAccentColor: '#b06f80',
    badgeBg: '#6b4851',
    badgeText: '#fff0f3',
    bgGradient: 'from-[#26171b] via-[#3a252b] to-[#1c1114]',
    illustrationUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'A Thousand Years (Violin Duo)',
  },
  'botanical-emerald': {
    id: 'botanical-emerald',
    name: 'Imperial Emerald & Gold',
    subtitle: 'Lush conservatory greenery, gold leaf typography, and crisp linen cards',
    envelopeColor: '#1c4436',
    envelopeFlapColor: '#133328',
    waxSealBg: '#c29b38',
    waxSealBorder: '#dfb755',
    waxSealColor: '#133328',
    waxSealText: 'G&T',
    cardBg: '#fbfcf9',
    cardBorder: '#d6e2db',
    cardTextPrimary: '#163127',
    cardTextSecondary: '#476558',
    cardAccentColor: '#b8860b',
    badgeBg: '#1b4436',
    badgeText: '#f0fdf4',
    bgGradient: 'from-[#081813] via-[#0f2a20] to-[#05100c]',
    illustrationUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Bridal Chorus (Cello & Harp)',
  },
  'midnight-haunt': {
    id: 'midnight-haunt',
    name: 'Midnight Gothic Masquerade',
    subtitle: 'Dark velvet noir, blood-orange wax seal, candlelit glow & gothic raven stationery',
    envelopeColor: '#120f18',
    envelopeFlapColor: '#0a080f',
    waxSealBg: '#c2410c',
    waxSealBorder: '#ea580c',
    waxSealColor: '#fef08a',
    waxSealText: 'HAUNT',
    cardBg: '#09080d',
    cardBorder: '#271c38',
    cardTextPrimary: '#faf5ff',
    cardTextSecondary: '#c084fc',
    cardAccentColor: '#f97316',
    badgeBg: '#451a03',
    badgeText: '#fdba74',
    bgGradient: 'from-[#050407] via-[#140b22] to-[#040205]',
    illustrationUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/30/audio_2d8dfbf59c.mp3?filename=horror-background-atmosphere-126231.mp3',
    musicTitle: 'Danse Macabre & Haunted Cathedral Atmosphere',
    stationery: {
      linerId: 'haunted-gothic',
      stampId: 'gothic-raven',
      postmarkCity: 'SALEM MANOR',
      foilFinish: 'gold',
    },
  },
  'mermaid-lagoon': {
    id: 'mermaid-lagoon',
    name: 'Mermaid Magic & Under the Sea',
    subtitle: 'Sunlit turquoise water, iridescent pearl scales, shimmering golden seashell seal & tropical ocean breeze',
    envelopeColor: '#369da3',
    envelopeFlapColor: '#288388',
    waxSealBg: '#f6eddd',
    waxSealBorder: '#d4af37',
    waxSealColor: '#257075',
    waxSealText: 'MAYA',
    cardBg: '#f7fcfd',
    cardBorder: '#b9e8eb',
    cardTextPrimary: '#134e4a',
    cardTextSecondary: '#0d9488',
    cardAccentColor: '#d97706',
    badgeBg: '#115e59',
    badgeText: '#ccfbf1',
    bgGradient: 'from-[#0b2b2b] via-[#114b4f] to-[#082020]',
    illustrationUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a7351b.mp3?filename=tropical-summer-10959.mp3',
    musicTitle: 'Ocean Breeze & Tropical Ukulele Vibes',
    stationery: {
      linerId: 'mermaid-tail',
      stampId: 'pearl-seashell',
      postmarkCity: 'CORAL BAY · OCEAN SUITE',
      foilFinish: 'gold',
    },
  },
  'cyber-hackathon': {
    id: 'cyber-hackathon',
    name: 'Cyberpunk Matrix & Hackathon Sprint',
    subtitle: 'Dark terminal obsidian, neon cyan circuit traces, glowing microchip hologram seal & 48h synthwave energy',
    envelopeColor: '#0a0f1d',
    envelopeFlapColor: '#060a14',
    waxSealBg: '#0f172a',
    waxSealBorder: '#00ffcc',
    waxSealColor: '#00ffcc',
    waxSealText: 'HACK',
    cardBg: '#090d16',
    cardBorder: '#1e293b',
    cardTextPrimary: '#f8fafc',
    cardTextSecondary: '#94a3b8',
    cardAccentColor: '#00ffcc',
    badgeBg: '#1e1b4b',
    badgeText: '#a5b4fc',
    bgGradient: 'from-[#030712] via-[#0b1329] to-[#020617]',
    illustrationUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=cyberpunk-2099-10701.mp3',
    musicTitle: 'Cyberpunk 2099 & Deep Synthwave Sprint',
    stationery: {
      linerId: 'cyber-circuit',
      stampId: 'microchip-hologram',
      postmarkCity: 'SILICON VALLEY // CAMPUS SPRINT',
      foilFinish: 'silver',
    },
  },
};

export const INITIAL_WEDDING_DATA: WeddingData = {
  id: 'wed-001',
  slug: 'liam-and-scarlett',
  coupleName1: 'Liam',
  coupleName2: 'Scarlett',
  coupleInitials: 'L&S',
  subtitleIntro: 'INTRODUCING',
  headline: 'PLEASE JOIN US FOR THE WEDDING OF',
  weddingDate: '2027-08-11',
  weddingTime: '3:45 PM',
  venueName: 'Cable Bay Vineyard',
  venueAddress: '12 Nick Johnstone Drive, Oneroa',
  cityState: 'Waiheke Island, New Zealand',
  mapsUrl: 'https://maps.google.com/?q=Cable+Bay+Vineyard+Waiheke+Island',
  rsvpDeadline: 'June 15, 2027',
  themeId: 'olive-burgundy',
  rsvpSurvey: DEFAULT_RSVP_SURVEY,
  transportInfo: 'On the day, return transport will be arranged from central Oneroa and the ferry wharf to Cable Bay Vineyard and back after the reception.',
  giftRegistryUrl: 'https://www.zola.com/registry',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
  timeline: [
    {
      id: 't-1',
      time: '3:45 PM',
      title: 'Guest Arrival & Champagne Welcome',
      description: 'Guests arrive at the glasshouse terrace for sparkling wine and live acoustic harp.',
      icon: 'cocktail',
    },
    {
      id: 't-2',
      time: '4:15 PM',
      title: 'The Wedding Ceremony',
      description: 'Exchange of vows overlooking the panoramic bay vineyards.',
      icon: 'ceremony',
    },
    {
      id: 't-3',
      time: '5:00 PM',
      title: 'Cocktails & Canapes',
      description: 'Sunset drinks, gourmet oyster bar, and lawn games in the olive grove.',
      icon: 'cocktail',
    },
    {
      id: 't-4',
      time: '7:00 PM',
      title: 'Seated Dinner & Speeches',
      description: 'Five-course farm-to-table wine pairing dinner followed by champagne toasts.',
      icon: 'toast',
    },
    {
      id: 't-5',
      time: '8:30 PM',
      title: 'Cutting the Wedding Cake',
      description: 'Sweet moments, espresso bar, and artisan dessert table.',
      icon: 'cake',
    },
    {
      id: 't-6',
      time: '9:00 PM - Midnight',
      title: 'First Dance & Dancing Time',
      description: 'Live 7-piece band and open cocktail bar to dance the night away.',
      icon: 'dancing',
    },
  ],
  hotels: [
    {
      id: 'h-1',
      name: 'Oneroa Bay Luxury Retreat',
      badge: '5 Min from Venue',
      description: 'Boutique waterfront villas with private infinity pools and coastal views.',
      bookingUrl: 'https://www.booking.com',
      discountCode: 'LIAMSCARLETT27',
      priceLevel: '$$$$',
    },
    {
      id: 'h-2',
      name: 'The Vineyard Estate Cottages',
      badge: 'On-site Partner',
      description: 'Charming rustic stone suites nestled right among the vines with breakfast included.',
      bookingUrl: 'https://www.airbnb.com',
      discountCode: 'WEDDINGGUEST',
      priceLevel: '$$$',
    },
  ],
  dressCode: {
    title: 'Dress to Impress',
    subtitle: 'Black Tie Optional / Vineyard Elegance',
    description: "We would love for you to join us celebrating in style in formal vineyard attire. For the ladies, floor-length or elevated midi dresses in rich tones. For gentlemen, dark suits or classic tuxedos.",
    swatches: [
      { name: 'Olive Green', hex: '#4e5b30' },
      { name: 'Deep Burgundy', hex: '#671928' },
      { name: 'Warm Terracotta', hex: '#93543d' },
      { name: 'Champagne Gold', hex: '#d4af37' },
      { name: 'Black Tie Noir', hex: '#1c1c1c' },
    ],
  },
  menu: [
    {
      id: 'm-1',
      course: 'Canapés & Starters',
      title: 'Seared King Salmon & Caviar',
      description: 'Pan-seared Ora King Salmon, dill emulsion, crisp capers & Oscietra caviar.',
      dietaryTags: ['Gluten-Free']
    },
    {
      id: 'm-2',
      course: 'Canapés & Starters',
      title: 'Truffle & Wild Porcini Arancini',
      description: 'Crispy carnaroli risotto pearls, aged Parmesan fonduta & black summer truffle.',
      dietaryTags: ['Vegetarian']
    },
    {
      id: 'm-3',
      course: 'Main Entrée',
      title: 'Prime Angus Beef Tenderloin',
      description: 'Charred broccolini, confit garlic potato purée, and 48-hour bone marrow jus.',
      dietaryTags: ['Gluten-Free']
    },
    {
      id: 'm-4',
      course: 'Main Entrée',
      title: 'Heirloom Roasted Butternut Risotto',
      description: 'Acquerello rice, crispy sage, toasted pine nuts, and vegan Parmesan crisp.',
      dietaryTags: ['Vegan', 'Gluten-Free']
    },
    {
      id: 'm-5',
      course: 'Dessert & Cake',
      title: 'Madagascan Vanilla & Gold Leaf Cake',
      description: 'Layered chiffon sponge, passionfruit curd, and champagne buttercream.',
      dietaryTags: ['Vegetarian']
    },
    {
      id: 'm-6',
      course: 'Signature Cocktails',
      title: 'The Golden Vow (French 75)',
      description: 'Botanical artisanal gin, lemon essence, raw sugar, topped with vintage champagne.',
      dietaryTags: []
    }
  ],
  storyTitle: 'From Paris to Forever',
  storyText: 'We met on a rainy autumn evening in Montmartre, Paris. Five years, countless adventures across 14 countries, and a sunset proposal on the Amalfi cliffs later — we are beyond ecstatic to begin this next chapter with our dearest family and friends.',
  faqs: [
    {
      id: 'f-1',
      question: 'What is the dress code?',
      answer: 'Our dress code is Black Tie Optional / Formal Vineyard Elegance. Dark suits, tuxedos, and floor-length or elevated midi gowns are welcome.'
    },
    {
      id: 'f-2',
      question: 'Are children invited?',
      answer: 'While we adore your little ones, our ceremony and reception are strictly an adult-only celebration.'
    },
    {
      id: 'f-3',
      question: 'Is there parking available?',
      answer: 'Yes, complimentary valet parking is provided upon arrival at the venue gates.'
    },
    {
      id: 'f-4',
      question: 'Can I bring a guest / Plus One?',
      answer: 'Due to venue intimacy, seats are reserved exclusively for the guests named on your invitation.'
    }
  ],
  photos: [
    {
      id: 'p-1',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
      caption: 'Where it all started - Paris, 2021',
      dateTag: 'October 2021',
    },
    {
      id: 'p-2',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
      caption: 'She said YES on the Amalfi Coast!',
      dateTag: 'September 2024',
    },
    {
      id: 'p-3',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
      caption: 'Counting down the days with you',
      dateTag: 'Summer 2026',
    },
  ],
};

export const SAMPLE_HALLOWEEN_PARTY_DATA: WeddingData = {
  id: 'halloween-sample-001',
  slug: 'midnight-masquerade-2026',
  eventType: 'halloween',
  eventTitle: 'The Midnight Gothic Masquerade',
  coupleName1: 'Lord Lucien & Lady Morgana',
  coupleName2: 'Ravenswood Manor',
  coupleInitials: 'HAUNT',
  subtitleIntro: 'ENTER IF YOU DARE',
  headline: 'YOU ARE CORDIALLY INVITED TO THE ANNUAL',
  weddingDate: '2026-10-31',
  weddingTime: '7:30 PM - 2:00 AM (The Witching Hour)',
  venueName: 'Ravenswood Gothic Manor & Obsidian Ballroom',
  venueAddress: '13 Blackwood Hollow Way, Salem',
  cityState: 'Massachusetts 01970',
  mapsUrl: 'https://maps.google.com/?q=Salem+Massachusetts',
  rsvpDeadline: 'October 20, 2026',
  themeId: 'midnight-haunt',
  storyTitle: 'The Legend of the Witching Hour Gathering',
  storyText: 'Once every century, when the blood moon rises over Salem and autumn mist blankets the ancient cedar forest, the gates of Ravenswood Manor swing open. Step beyond the wrought-iron archway into an enchanting evening of candlelit decadence, wicked illusionists, arcane melodies, dry-ice potion bars, and midnight revelry.',
  transportInfo: 'On All Hallows’ Eve, complimentary guest shuttles will depart from Salem Central Station every 30 minutes. Valet carriage parking is also available at the manor gates.',
  giftRegistryUrl: '',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/10/30/audio_2d8dfbf59c.mp3?filename=horror-background-atmosphere-126231.mp3',
  rsvpSurvey: {
    allowPlusOnes: true,
    maxPlusOnes: 2,
    askMealPreference: true,
    mealOptions: [
      'Charred Black Angus Filet (Squid-Ink Jus & Truffle Purée)',
      'Wild Forest Porcini & Ash Gnocchi (Vegetarian / Truffle Foam)',
      'Smoked Butternut & Cauldron Vegetable Ragout (Vegan / GF)',
    ],
    askDietaryRestrictions: true,
    dietaryOptions: [
      'Gluten-Free',
      'Vegetarian',
      'Vegan',
      'Dairy-Free',
      'Nut Allergy',
      'Garlic-Free (Vampire Safe)',
    ],
    askSongRequest: true,
    songRequestPrompt: 'What dark synthwave or haunting anthem will summon you to the dance floor?',
    askPersonalMessage: true,
    customQuestions: [
      {
        id: 'q-costume',
        question: 'What costume concept or alter ego will you be embodying?',
        placeholder: 'e.g. Victorian Vampire Lord, Gothic Raven Queen, 1920s Phantom',
        required: true,
      },
      {
        id: 'q-shuttle',
        question: 'Will you be taking the Salem Manor Guest Shuttle?',
        placeholder: 'Yes, from Salem Station / Driving & Valet',
        required: false,
      },
    ],
  },
  timeline: [
    {
      id: 't-1',
      time: '7:30 PM',
      title: 'Gate Unlocking & Absinthe Welcome',
      description: 'Cauldron cocktails with dry ice mist, blood-orange bellinis, and live gothic harp beneath candelabras.',
      icon: 'cocktail',
    },
    {
      id: 't-2',
      time: '8:30 PM',
      title: 'The Grand Masquerade Promenade',
      description: 'Opulent costume promenade and the ceremony of the unmasking waltz in the Grand Ballroom.',
      icon: 'ceremony',
    },
    {
      id: 't-3',
      time: '9:30 PM',
      title: 'Wicked Banquet & Potion Tasting',
      description: '4-course dark culinary feast with smoked prime meats, black truffle pasta, and crimson velvet pastries.',
      icon: 'toast',
    },
    {
      id: 't-4',
      time: '10:45 PM',
      title: 'Annual Costume Contest & Awards',
      description: 'Trophies and champagne magnums awarded for Best Gothic Noir, Most Terrifying, and Best Duo.',
      icon: 'cake',
    },
    {
      id: 't-5',
      time: '11:59 PM',
      title: 'The Witching Hour Toast',
      description: 'The historic manor bells toll at midnight followed by a sparkling phantom toast.',
      icon: 'cocktail',
    },
    {
      id: 't-6',
      time: '12:15 AM - Late',
      title: 'Danse Macabre & Crypt Afterparty',
      description: 'Dark wave DJ, vinyl waltzes, and secret underground speakeasy bar open till 2 AM.',
      icon: 'dancing',
    },
  ],
  dressCode: {
    title: 'Gothic Masquerade & Dark Academia Chic',
    subtitle: 'Costumes or Opulent Black-Tie Noir Mandatory',
    description: 'All guests are strictly requested to wear full masquerade costumes, Venetian masks, velvet capes, Victorian lace, or formal dark eveningwear.',
    swatches: [
      { name: 'Obsidian Velvet', hex: '#09080d' },
      { name: 'Blood Orange Ember', hex: '#c2410c' },
      { name: 'Royal Amethyst', hex: '#581c87' },
      { name: 'Candlelight Gold', hex: '#d97706' },
      { name: 'Crimson Wine', hex: '#881337' },
    ],
  },
  menu: [
    {
      id: 'm-1',
      course: 'Signature Cocktails',
      title: 'Blackberry Bourbon Black Magic',
      description: 'Smoked small-batch bourbon, activated charcoal, blackberry liqueur & dry-ice cauldron smoke.',
      dietaryTags: ['Signature Potion'],
    },
    {
      id: 'm-2',
      course: 'Signature Cocktails',
      title: 'Vampire Blood Prosecco Spritz',
      description: 'Blood orange essence, Campari, pomegranate pearls & burnt rosemary branch.',
      dietaryTags: ['Gluten-Free', 'Vegan'],
    },
    {
      id: 'm-3',
      course: 'Canapés & Starters',
      title: 'Truffle & Squid-Ink Arancini',
      description: 'Crispy obsidian carnaroli rice, black summer truffle, and smoked parmesan fondue.',
      dietaryTags: ['Vegetarian'],
    },
    {
      id: 'm-4',
      course: 'Main Entrée',
      title: 'Charred Black Angus & Truffle Crypt',
      description: 'Prime dry-aged filet, squid-ink bone marrow reduction, and charred heritage carrots.',
      dietaryTags: ['Gluten-Free'],
    },
    {
      id: 'm-5',
      course: 'Main Entrée',
      title: 'Wild Forest Porcini & Ash Gnocchi',
      description: 'Handmade potato-ash gnocchi, black trumpet mushrooms, and garlic-herb cream.',
      dietaryTags: ['Vegetarian'],
    },
    {
      id: 'm-6',
      course: 'Dessert & Cake',
      title: 'Bleeding Red Velvet Poison Cake',
      description: 'Dark cocoa velvet sponge, tart raspberry blood coulis, and spun-sugar cobwebs.',
      dietaryTags: ['Vegetarian'],
    },
  ],
  hotels: [
    {
      id: 'h-1',
      name: 'The Hawthorne Historic Witch Hotel',
      badge: '10 Min from Manor',
      description: 'Legendary 1920s historic hotel in central Salem with vintage charm and speakeasy lounge.',
      bookingUrl: 'https://www.booking.com',
      discountCode: 'SALEMHAUNT26',
      priceLevel: '$$$',
    },
    {
      id: 'h-2',
      name: 'The Merchant Salem Boutique Suites',
      badge: 'Partner Lodging',
      description: 'Modern gothic luxury boutique inn with heated fireplaces and complimentary breakfast.',
      bookingUrl: 'https://www.airbnb.com',
      discountCode: 'RAVENSWOOD',
      priceLevel: '$$$$',
    },
  ],
  faqs: [
    {
      id: 'f-1',
      question: 'Are Venetian or masquerade masks mandatory?',
      answer: 'Yes! All guests must arrive in a masquerade mask or full costume character. Masks will be worn until the Grand Unmasking Promenade at 8:30 PM.',
    },
    {
      id: 'f-2',
      question: 'What are the costume contest categories and prizes?',
      answer: 'Trophies and prizes will be awarded for: Best Overall Masquerade ($500 grand prize), Most Terrifying & Atmospheric, and Best Duo / Couple Ensemble.',
    },
    {
      id: 'f-3',
      question: 'Will there be non-alcoholic potions and mocktails?',
      answer: 'Yes! Our alchemist bar features handcrafted zero-proof potions including Blackberry Fog Spritz, Smoked Spiced Cider, and Crimson Pomegranate Fizz.',
    },
    {
      id: 'f-4',
      question: 'How do I access the manor and parking?',
      answer: 'Complimentary valet parking is available at the front wrought-iron gates. Alternatively, our complimentary guest shuttle runs continuously from Salem Station.',
    },
  ],
  photos: [
    {
      id: 'p-1',
      url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
      caption: 'The ancient wrought-iron gates of Ravenswood Manor shrouded in Salem fog',
      dateTag: 'All Hallows’ Eve',
    },
    {
      id: 'p-2',
      url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1200&q=80',
      caption: 'Venetian skull masquerade & glowing candlelit Jack-o’-Lanterns for the Grand Promenade',
      dateTag: 'Costume Showcase',
    },
    {
      id: 'p-3',
      url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
      caption: 'The Obsidian Grand Ballroom illuminated by 500 beeswax taper candles',
      dateTag: 'The Witching Hour',
    },
    {
      id: 'p-4',
      url: 'https://images.unsplash.com/photo-1509557965875-b88c97052f0e?auto=format&fit=crop&w=1200&q=80',
      caption: 'Alchemist cauldron potion bar featuring dry-ice elixirs, skulls & dark alchemy',
      dateTag: 'Potion Cellar',
    },
    {
      id: 'p-5',
      url: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80',
      caption: 'Carved Jack-o’-Lanterns casting eerie shadows along the cemetery garden path',
      dateTag: 'Midnight Promenade',
    },
    {
      id: 'p-6',
      url: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=1200&q=80',
      caption: 'The Secret Crypt Library & Midnight Séance Chamber',
      dateTag: 'Danse Macabre',
    },
  ],
};

export interface MermaidAgeMilestone {
  age: number;
  pun: string;
  headline: string;
  subtitle: string;
  bannerTag: string;
}

export const MERMAID_AGE_MILESTONES: Record<number, MermaidAgeMilestone> = {
  1: {
    age: 1,
    pun: 'Sweet One Under The Sea',
    headline: 'OUR LITTLE MERMAID IS TURNING ONE!',
    subtitle: 'MAKE A SPLASH TO CELEBRATE OUR SWEET ONE',
    bannerTag: 'First Birthday Milestone',
  },
  2: {
    age: 2,
    pun: 'Two Cool By The Pool',
    headline: 'SPLISH SPLASH! OUR MERMAID IS TURNING TWO!',
    subtitle: 'JOIN US FOR SUNSHINE & WATER PLAY',
    bannerTag: 'Toddler Splash Party',
  },
  3: {
    age: 3,
    pun: 'Three Wishes Under The Sea',
    headline: 'MAGICAL SEASHELLS & THREE BIRTHDAY WISHES!',
    subtitle: 'JOIN OUR MERMAID COVE CELEBRATION',
    bannerTag: 'Magical 3rd Birthday',
  },
  4: {
    age: 4,
    pun: 'Fin-tastic Four',
    headline: 'OUR LITTLE MERMAID IS FIN-TASTIC FOUR!',
    subtitle: 'SWIM ON OVER FOR A MERMAID BIRTHDAY FIESTA',
    bannerTag: 'Fin-tastic 4th Celebration',
  },
  5: {
    age: 5,
    pun: 'Dive Into Five',
    headline: 'DIVE INTO FIVE! SPLISH SPLASH BIRTHDAY BASH',
    subtitle: 'GRAB YOUR MERMAID TAILS & TOWELS FOR',
    bannerTag: '#1 Most Popular Celebration',
  },
  6: {
    age: 6,
    pun: 'Seven Seas Six',
    headline: 'MAKING WAVES AS SHE TURNS SIX!',
    subtitle: 'JOIN US FOR A SPARKLING MERMAID SPLASH PARTY',
    bannerTag: 'Sensational 6th Birthday',
  },
  7: {
    age: 7,
    pun: 'Lucky Seven Ocean Adventure',
    headline: 'SEVEN WONDERS OF THE SEA! TURNING SEVEN',
    subtitle: 'JOIN OUR MERMAID LAGOON TREASURE HUNT',
    bannerTag: 'Lucky 7th Adventure',
  },
  8: {
    age: 8,
    pun: 'Eight & Fin-tastic',
    headline: 'CELEBRATING EIGHT MAGICAL OCEANS OF FUN',
    subtitle: 'DIVE DEEP FOR AN UNFORGETTABLE MERMAID GALA',
    bannerTag: 'Great 8th Gala',
  },
};

export const SAMPLE_MERMAID_PARTY_DATA: WeddingData = {
  id: 'mermaid-sample-001',
  slug: 'maya-mermaid-pool-party',
  eventType: 'kids_party',
  eventTitle: 'Dive Into Five! Mermaid Birthday & Pool Party',
  honoreeName: 'Maya',
  coupleName1: 'Maya Reynolds',
  coupleName2: 'Turning 5!',
  coupleInitials: 'MAYA',
  ageMilestone: 5,
  milestonePun: 'Dive Into Five',
  subtitleIntro: 'GRAB YOUR MERMAID TAILS & TOWELS FOR',
  headline: 'DIVE INTO FIVE! SPLISH SPLASH BIRTHDAY BASH CELEBRATING',
  weddingDate: '2026-07-18',
  weddingTime: '1:00 PM - 4:30 PM',
  venueName: 'The Reynolds Backyard Resort & Pool',
  venueAddress: '422 Coral Reef Way, Laguna Beach',
  cityState: 'California 92651',
  mapsUrl: 'https://maps.google.com/?q=Laguna+Beach+CA',
  rsvpDeadline: 'July 5, 2026',
  themeId: 'mermaid-lagoon',
  stationery: {
    linerId: 'mermaid-tail',
    stampId: 'pearl-seashell',
    postmarkCity: 'CORAL BAY · POOL SUITE',
    foilFinish: 'gold',
  },
  storyTitle: 'A Magical "Dive Into Five" Mermaid Adventure!',
  storyText: 'Dive into an afternoon of swimming, poolside games, underwater treasure hunts, and mermaid cupcakes! We will have certified lifeguards on duty, fun pool floats, glitter sunscreen, and plenty of mermaid magic for all our little swimmers and families.',
  transportInfo: 'Street parking is readily available along Coral Reef Way. Please bring swimsuits, flip flops, and goggles! Towels, sunscreen, and pool floats are fully provided.',
  giftRegistryUrl: '',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a7351b.mp3?filename=tropical-summer-10959.mp3',
  rsvpSurvey: {
    allowPlusOnes: true,
    maxPlusOnes: 3,
    askMealPreference: true,
    mealOptions: [
      'Mermaid Artisan Pizza (Cheese & Pepperoni)',
      'Poolside Mini Sliders & Curly Fries',
      'Fresh Fruit Skewers & Veggie Dippers (Vegan / GF)',
      'Crispy Chicken Tenders (Gluten-Free)',
    ],
    askDietaryRestrictions: true,
    dietaryOptions: [
      'Gluten-Free',
      'Nut Allergy',
      'Dairy-Free',
      'Vegetarian',
      'Egg Allergy',
    ],
    askSongRequest: true,
    songRequestPrompt: 'What fun dance song will get your swimmer dancing by the pool?',
    askPersonalMessage: true,
    customQuestions: [
      {
        id: 'q-swimmer',
        question: "Child's Swimming Comfort Level",
        placeholder: 'e.g. Needs puddle jumper / Shallow end only / Confident swimmer',
        required: true,
      },
      {
        id: 'q-parent-contact',
        question: 'Parent / Guardian Phone Number',
        placeholder: '(555) 000-0000',
        required: true,
      },
    ],
  },
  timeline: [
    {
      id: 't-1',
      time: '1:00 PM',
      title: 'Arrival & Sunscreen Station',
      description: 'Grab your mermaid goggles, pick your pool float, and lather up with sparkling sunscreen!',
      icon: 'cocktail',
    },
    {
      id: 't-2',
      time: '1:30 PM',
      title: 'Pool Games & Underwater Treasure Hunt',
      description: 'Dive for sunken jewels, pool noodle races, and floating splash targets with fun prizes!',
      icon: 'ceremony',
    },
    {
      id: 't-3',
      time: '2:45 PM',
      title: 'Mermaid Pizza & Tropical Juice Bar',
      description: 'Poolside lunch with fresh wood-fired pizza, watermelon pops, and ocean blue punch!',
      icon: 'dinner',
    },
    {
      id: 't-4',
      time: '3:30 PM',
      title: 'Cake Cutting & Birthday Songs',
      description: 'Singing happy birthday to Maya around the shimmering seashell birthday cake!',
      icon: 'cake',
    },
    {
      id: 't-5',
      time: '4:00 PM',
      title: 'Water Balloon Splash & Goodie Bags',
      description: 'Epic fun splash finale and custom mermaid tail goodie bags for all the little guests!',
      icon: 'sparklers',
    },
  ],
  dressCode: {
    title: 'Poolside Chic & Swimwear',
    subtitle: 'Bring Your Favorite Swimsuits & Flip Flops',
    description: 'Come dressed in swimsuits ready to splash! Towels, sunglasses, pool noodles, and sun lotion are provided. Parents are welcome to lounge poolside in casual summer attire.',
    swatches: [
      { name: 'Aqua Turquoise', hex: '#48b2b7' },
      { name: 'Coral Pink', hex: '#f472b6' },
      { name: 'Sunlit Gold', hex: '#fbbf24' },
      { name: 'Seafoam Mint', hex: '#a7f3d0' },
      { name: 'Ocean Pearl', hex: '#f0fdfa' },
    ],
  },
  menu: [
    {
      id: 'm-1',
      course: 'Canapés & Starters',
      title: 'Watermelon Mermaid Pops & Starfish Pretzels',
      description: 'Fresh sliced watermelon starfish on sticks with cinnamon honey dip.',
      dietaryTags: ['Kids Favorite', 'Gluten-Free'],
    },
    {
      id: 'm-2',
      course: 'Main Entrée',
      title: 'Artisan Wood-Fired Poolside Pizza',
      description: 'Crispy mozzarella cheese, sweet marinara, pepperoni & gluten-free crust options.',
      dietaryTags: ['Freshly Baked'],
    },
    {
      id: 'm-3',
      course: 'Dessert & Cake',
      title: 'Shimmering Scallop Seashell Cake & Pearl Cupcakes',
      description: 'Vanilla bean sponge with ocean blue buttercream, pearl sprinkles & edible glitter.',
      dietaryTags: ['Birthday Cake'],
    },
    {
      id: 'm-4',
      course: 'Signature Cocktails',
      title: 'Ocean Breeze Blue Mocktail & Tropical Lemonade',
      description: 'Blue raspberry swirl lemonade with gummy fish garnish and paper umbrellas.',
      dietaryTags: ['Non-Alcoholic'],
    },
  ],
  hotels: [],
  faqs: [
    {
      id: 'f-1',
      question: 'Will there be a lifeguard on duty?',
      answer: 'Yes! We have hired two certified Red Cross lifeguards who will actively monitor the pool throughout the entire event.',
    },
    {
      id: 'f-2',
      question: 'What should my child bring?',
      answer: 'Just a swimsuit, flip flops, and goggles! Towels, sunscreen, life vests, puddle jumpers, and pool toys will all be provided.',
    },
    {
      id: 'f-3',
      question: 'Can parents stay and hang out?',
      answer: 'Absolutely! We have shaded cabanas, iced drinks, charcuterie, and lounge chairs for all parents who wish to stay and relax.',
    },
  ],
  photos: [
    {
      id: 'p-1',
      url: '/assets/mermaid/mermaid_invite_card.jpg',
      caption: 'Official "Dive Into Five" Mermaid Invitation Stationery Card',
      dateTag: 'Signature Gold Foil Edition',
    },
    {
      id: 'p-2',
      url: '/assets/mermaid/mermaid_multidevice_mockup.jpg',
      caption: 'Interactive 3D Smartphone & Tablet Guest Unboxing',
      dateTag: 'Digital Experience',
    },
    {
      id: 'p-3',
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      caption: 'Sunlit turquoise waters & summer pool day vibes',
      dateTag: 'Laguna Beach Pool',
    },
    {
      id: 'p-4',
      url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
      caption: 'Mermaid magic & summer poolside smiles',
      dateTag: 'Maya turns 5!',
    },
    {
      id: 'p-5',
      url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80',
      caption: 'Colorful party balloons & poolside games',
      dateTag: 'Splish Splash Fun',
    },
    {
      id: 'p-4',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
      caption: 'Mermaid tail cupcakes & sparkling treats',
      dateTag: 'Sweet Table',
    },
  ],
};

export const INITIAL_RSVPS: RSVPRecord[] = [
  {
    id: 'rsvp-1',
    weddingId: 'wed-001',
    guestName: 'Eleanor Vance',
    guestEmail: 'eleanor.vance@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Julian Vance'],
    mealChoice: 'Charred Prime Beef Tenderloin',
    dietaryNotes: 'Gluten-free for Eleanor',
    songRequest: 'At Last - Etta James',
    personalMessage: 'So incredibly thrilled for you both! Can not wait to celebrate under the stars!',
    submittedAt: '2026-08-14T10:30:00Z',
  },
  {
    id: 'rsvp-2',
    weddingId: 'wed-001',
    guestName: 'Marcus Sterling',
    guestEmail: 'marcus.s@example.com',
    attendance: 'attending',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'Crispy Skin King Salmon',
    dietaryNotes: 'None',
    songRequest: 'September - Earth, Wind & Fire',
    personalMessage: 'Ready for the greatest party of 2027!',
    submittedAt: '2026-08-15T14:12:00Z',
  },
  {
    id: 'rsvp-3',
    weddingId: 'wed-001',
    guestName: 'Sophia Montgomery',
    guestEmail: 'sophia.m@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Lucas Montgomery'],
    mealChoice: 'Wild Mushroom & Truffle Risotto (V)',
    dietaryNotes: 'Vegetarian',
    songRequest: 'Lover - Taylor Swift',
    personalMessage: 'Liam & Scarlett, you two are pure magic. See you on Waiheke!',
    submittedAt: '2026-08-16T09:45:00Z',
  },
  {
    id: 'rsvp-4',
    weddingId: 'wed-001',
    guestName: 'Arthur Pendelton',
    guestEmail: 'arthur.p@example.com',
    attendance: 'declined',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'N/A',
    dietaryNotes: '',
    personalMessage: 'Sending all our love from London! Sadly cannot make the flight but will be toasting with champagne!',
    submittedAt: '2026-08-16T16:20:00Z',
  },
];

export const INITIAL_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ord-8891',
    claimCode: 'ETSY-OLIVE-9482',
    platform: 'Etsy',
    buyerName: 'Charlotte Miller',
    buyerEmail: 'charlotte.m@gmail.com',
    themeSelected: 'olive-burgundy',
    orderStatus: 'claimed',
    createdAt: '2026-09-08 19:30',
    claimedAt: '2026-09-08 20:15',
  },
  {
    id: 'ord-8892',
    claimCode: 'GUM-CHAMP-1029',
    platform: 'Gumroad',
    buyerName: 'Benjamin Hayes',
    buyerEmail: 'ben.hayes@outlook.com',
    themeSelected: 'champagne-noir',
    orderStatus: 'generated',
    createdAt: '2026-09-09 08:45',
  },
  {
    id: 'ord-8893',
    claimCode: 'ETSY-TUSCAN-7734',
    platform: 'Etsy',
    buyerName: 'Isabella Rossi',
    buyerEmail: 'isabella.r@gmail.com',
    themeSelected: 'tuscan-terracotta',
    orderStatus: 'published',
    createdAt: '2026-09-07 14:10',
    claimedAt: '2026-09-07 15:00',
  }
];

export const CURATED_MUSIC_OPTIONS: MusicTrack[] = [
  {
    id: 'piano-romance',
    title: 'Cinematic Piano Romance',
    artist: 'Eternelle Studio',
    genre: 'Solo Piano',
    duration: '2:45',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    description: 'Heartfelt, emotional solo piano ballad with classic romantic chords.',
  },
  {
    id: 'acoustic-vows',
    title: 'Acoustic Sunset Guitar',
    artist: 'Acoustic Serenade',
    genre: 'Fingerstyle Guitar',
    duration: '3:12',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=acoustic-guitar-wedding-18088.mp3',
    description: 'Warm fingerpicked acoustic guitar suited for outdoor, rustic & coastal weddings.',
  },
  {
    id: 'harp-celestial',
    title: 'Celestial Wedding Harp',
    artist: 'St. Claire Ensemble',
    genre: 'Cathedral Harp',
    duration: '2:15',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=wedding-harp-10548.mp3',
    description: 'Ethereal angelic harp arpeggios providing pure fairy-tale luxury.',
  },
  {
    id: 'royal-strings',
    title: 'Bridgerton String Quartet',
    artist: 'Mayfair Chamber Players',
    genre: 'String Quartet',
    duration: '3:30',
    url: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=cinematic-strings-wedding-6430.mp3',
    description: 'Opulent violin and cello arrangement for grand ballroom ceremonies.',
  },
  {
    id: 'lofi-twilight',
    title: 'Twilight Lo-Fi Vows',
    artist: 'Sunset Chords',
    genre: 'Modern Ambient Lo-Fi',
    duration: '2:50',
    url: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f77c30.mp3?filename=lofi-romance-124018.mp3',
    description: 'Modern, chill romantic beat with soft tape-decay Rhodes piano.',
  },
];

export const DEFAULT_EVENT_BLOCKS: Record<string, EventBlockConfig[]> = {
  wedding: [
    { id: 'story', title: 'Our Love Story', icon: '❤️', enabled: true },
    { id: 'schedule', title: 'Order of Events', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Food & Drinks Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Photo Gallery', icon: '📸', enabled: true },
    { id: 'attire', title: 'Dress Code & Palette', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: true },
    { id: 'faqs', title: 'Guest Q&A / FAQs', icon: '❓', enabled: true },
  ],
  engagement: [
    { id: 'story', title: 'The Proposal Story', icon: '💍', enabled: true },
    { id: 'schedule', title: 'Celebration Timeline', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Cocktails & Canapés', icon: '🍸', enabled: true },
    { id: 'gallery', title: 'Engagement Portraits', icon: '📸', enabled: true },
    { id: 'attire', title: 'Cocktail Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Party Details & FAQs', icon: '❓', enabled: true },
  ],
  birthday: [
    { id: 'story', title: 'A Chapter of Memories', icon: '✨', enabled: true },
    { id: 'schedule', title: 'Party Schedule', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Birthday Bites & Bar', icon: '🎂', enabled: true },
    { id: 'gallery', title: 'Memory Reel', icon: '📸', enabled: true },
    { id: 'attire', title: 'Party Theme & Attire', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Party Info & Wishlist', icon: '❓', enabled: true },
  ],
  halloween: [
    { id: 'story', title: 'The Witching Hour & Haunt Lore', icon: '🕯️', enabled: true },
    { id: 'schedule', title: 'Order of Haunts & Timeline', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Wicked Cocktails & Potion Bar', icon: '🍸', enabled: true },
    { id: 'gallery', title: 'Costume Gallery & Past Haunts', icon: '📸', enabled: true },
    { id: 'attire', title: 'Costume Theme & Contest Guide', icon: '🎭', enabled: true },
    { id: 'hotels', title: 'Nearby Haunted Inns & Stays', icon: '🏰', enabled: false },
    { id: 'faqs', title: 'Party Rules & Witching FAQs', icon: '🦇', enabled: true },
  ],
  anniversary: [
    { id: 'story', title: 'Years of Love Timeline', icon: '🥂', enabled: true },
    { id: 'schedule', title: 'Toast & Dinner Schedule', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Anniversary Dinner Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Journey Through the Years', icon: '📸', enabled: true },
    { id: 'attire', title: 'Attire & Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Hotel Recommendations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Guest FAQs', icon: '❓', enabled: true },
  ],
  baby_shower: [
    { id: 'story', title: 'Welcoming Our Little Blessing', icon: '🍼', enabled: true },
    { id: 'schedule', title: 'Shower Schedule & Games', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Sweets & Refreshments', icon: '🧁', enabled: true },
    { id: 'gallery', title: 'Maternity Moments', icon: '📸', enabled: true },
    { id: 'attire', title: 'Theme & Pastel Palette', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Travel & Accommodations', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Registry & Diaper Raffle', icon: '🎁', enabled: true },
  ],
  gala: [
    { id: 'story', title: 'Mission & Keynote Vision', icon: '🎙️', enabled: true },
    { id: 'schedule', title: 'Gala Evening Itinerary', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Banquet & Wine Pairings', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Past Gala Highlights', icon: '📸', enabled: true },
    { id: 'attire', title: 'Black-Tie Dress Code', icon: '👗', enabled: true },
    { id: 'hotels', title: 'VIP Accommodations & Travel', icon: '🏨', enabled: true },
    { id: 'faqs', title: 'Sponsorship & Seating FAQs', icon: '❓', enabled: true },
  ],
  kids_party: [
    { id: 'story', title: 'Celebration Honoree & Theme', icon: '🧜‍♀️', enabled: true },
    { id: 'schedule', title: 'Party Timeline & Activities', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Mermaid Treats & Refreshments', icon: '🧁', enabled: true },
    { id: 'gallery', title: 'Fun Photo Reel', icon: '📸', enabled: true },
    { id: 'attire', title: 'Theme Attire & Dress Code', icon: '🩱', enabled: true },
    { id: 'hotels', title: 'Location & Arrival Details', icon: '📍', enabled: false },
    { id: 'faqs', title: 'Guest FAQs & Party Notes', icon: '❓', enabled: true },
  ],
  hackathon: [
    { id: 'story', title: 'Mission & Problem Statements', icon: '💻', enabled: true },
    { id: 'schedule', title: '48-Hour Hackathon Timeline', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Hacker Fuel, Red Bull & Pizza Drops', icon: '🍕', enabled: true },
    { id: 'gallery', title: 'Past Winners & Hack Gallery', icon: '🏆', enabled: true },
    { id: 'attire', title: 'Tracks, Rules & Devpost Criteria', icon: '📜', enabled: true },
    { id: 'hotels', title: 'Campus Labs, Sleeping Bays & Travel', icon: '🏢', enabled: true },
    { id: 'faqs', title: 'Hacker FAQs & Discord Portal', icon: '🤖', enabled: true },
  ],
  custom: [
    { id: 'story', title: 'About This Celebration', icon: '✨', enabled: true },
    { id: 'schedule', title: 'Order of Events', icon: '⏰', enabled: true },
    { id: 'menu', title: 'Food & Drinks Menu', icon: '🍽️', enabled: true },
    { id: 'gallery', title: 'Photo Highlights', icon: '📸', enabled: true },
    { id: 'attire', title: 'Attire & Theme', icon: '👗', enabled: true },
    { id: 'hotels', title: 'Accommodations & Travel', icon: '🏨', enabled: false },
    { id: 'faqs', title: 'Event FAQs', icon: '❓', enabled: true },
  ],
};

export const EVENT_CATEGORY_PRESETS: Record<string, EventCategoryPreset> = {
  wedding: {
    type: 'wedding',
    label: 'Wedding & Reception',
    badge: 'Couture Classic',
    icon: '💍',
    description: 'Ceremony, grand dinner, toasts, bridal party & honeymoon registry.',
    defaultHeadline: 'PLEASE JOIN US FOR THE WEDDING OF',
    defaultSubtitle: 'TOGETHER WITH THEIR FAMILIES',
    defaultStoryTitle: 'Our Love Story',
    defaultTheme: 'botanical-emerald',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.wedding,
  },
  engagement: {
    type: 'engagement',
    label: 'Engagement Party',
    badge: 'Chic Celebration',
    icon: '💎',
    description: 'Cocktail soirée, champagne toasts, and proposal celebration.',
    defaultHeadline: 'JOIN US TO CELEBRATE THE ENGAGEMENT OF',
    defaultSubtitle: 'POP THE CHAMPAGNE FOR',
    defaultStoryTitle: 'The Proposal',
    defaultTheme: 'dusty-rose',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.engagement,
  },
  birthday: {
    type: 'birthday',
    label: 'Birthday & Milestone',
    badge: 'Milestone Soirée',
    icon: '🎂',
    description: '1st, 18th, 21st, 30th, 40th, 50th and milestone birthday celebrations.',
    defaultHeadline: 'YOU ARE CORDIALLY INVITED TO CELEBRATE',
    defaultSubtitle: 'A SPECTACULAR MILESTONE',
    defaultStoryTitle: 'A Chapter of Memories',
    defaultTheme: 'champagne-noir',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.birthday,
  },
  halloween: {
    type: 'halloween',
    label: 'Halloween & Gothic Masquerade',
    badge: 'Wicked Glamour',
    icon: '🎃',
    description: 'Wicked costume contests, potion bars, witching hour schedule & dark aesthetics.',
    defaultHeadline: 'YOU ARE CORDIALLY INVITED TO THE ANNUAL',
    defaultSubtitle: 'ENTER IF YOU DARE',
    defaultStoryTitle: 'A Night of Wicked Glamour & Haunts',
    defaultTheme: 'midnight-haunt',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.halloween,
  },
  anniversary: {
    type: 'anniversary',
    label: 'Anniversary & Vow Renewal',
    badge: 'Golden Romance',
    icon: '🥂',
    description: 'Celebrating 10, 25, 50 years of love, memories and renewed vows.',
    defaultHeadline: 'CELEBRATING 25 YEARS OF LOVE & DEVOTION',
    defaultSubtitle: 'HONOURING THE ANNIVERSARY OF',
    defaultStoryTitle: '25 Years of Beautiful Memories',
    defaultTheme: 'tuscan-terracotta',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.anniversary,
  },
  baby_shower: {
    type: 'baby_shower',
    label: 'Baby Shower & Gender Reveal',
    badge: 'Sweet Welcome',
    icon: '🍼',
    description: 'Welcoming the new arrival with registry links and sweet festivities.',
    defaultHeadline: 'JOIN US IN CELEBRATING THE ARRIVAL OF',
    defaultSubtitle: 'A SWEET LITTLE BLESSING',
    defaultStoryTitle: 'Our Growing Family',
    defaultTheme: 'dusty-rose',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.baby_shower,
  },
  gala: {
    type: 'gala',
    label: 'Gala, Soirée & Charity Dinner',
    badge: 'Black-Tie Editorial',
    icon: '🍸',
    description: 'Formal charity galas, keynote banquets, and annual celebrations.',
    defaultHeadline: 'REQUESTS THE PLEASURE OF YOUR COMPANY AT',
    defaultSubtitle: 'ANNUAL CHARITY SOIREE',
    defaultStoryTitle: 'Our Mission & Vision',
    defaultTheme: 'champagne-noir',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.gala,
  },
  kids_party: {
    type: 'kids_party',
    label: 'Mermaid & Ocean Magic',
    badge: 'Under the Sea',
    icon: '🧜‍♀️',
    description: 'Magical mermaid birthdays, pool parties, under-the-sea baby showers, and ocean adventures.',
    defaultHeadline: 'DIVE UNDER THE SEA TO CELEBRATE',
    defaultSubtitle: 'JOIN US FOR A MAGICAL CELEBRATION FOR',
    defaultStoryTitle: 'A Magical Under-The-Sea Adventure',
    defaultTheme: 'mermaid-lagoon',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.kids_party,
  },
  hackathon: {
    type: 'hackathon',
    label: 'Collegiate Hackathon & Sprint',
    badge: 'Campus Innovation',
    icon: '⚡',
    description: '48H sprint countdown, $25K prize tracks, Discord onboarding, QR passes & mentor portals.',
    defaultHeadline: 'ANNUAL COLLEGIATE HACKATHON & INNOVATION SPRINT',
    defaultSubtitle: 'JOIN 500+ BUILDERS, DESIGNERS & FOUNDERS FOR',
    defaultStoryTitle: 'The Mission & Challenge Tracks',
    defaultTheme: 'cyber-hackathon',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.hackathon,
  },
  custom: {
    type: 'custom',
    label: 'Custom Milestone',
    badge: 'Bespoke Atelier',
    icon: '✨',
    description: 'Design your own custom celebration with bespoke titles and sections.',
    defaultHeadline: 'CORDIALLY INVITES YOU TO CELEBRATE',
    defaultSubtitle: 'AN EXCLUSIVE GATHERING',
    defaultStoryTitle: 'About This Event',
    defaultTheme: 'botanical-emerald',
    defaultBlocks: DEFAULT_EVENT_BLOCKS.custom,
  },
};

export const SAMPLE_HACKATHON_DATA: WeddingData = {
  id: 'demo-hackathon-2026',
  eventType: 'hackathon',
  eventTitle: 'CYBERHACKS 2026: Campus Innovation Sprint',
  honoreeName: 'Stanford & MIT Engineering Federation',
  hostNames: 'ACM & IEEE Student Chapters',
  prizePool: '$25,000 in Cash & Cloud Bounties',
  hackathonTracks: ['Artificial Intelligence / LLMs', 'Decentralized & Web3', 'Robotics & Embedded IoT', 'HealthTech & Biotech'],
  teamFormationEnabled: true,
  discordUrl: 'https://discord.gg/cyberhacks-campus',
  wifiInfo: 'SSID: Campus-HackNet / Key: hackthefuture2026',
  slug: 'cyberhacks-2026',
  coupleName1: 'CyberHacks 2026',
  coupleName2: 'Campus Edition',
  coupleInitials: 'CH',
  subtitleIntro: '> INITIALIZING HACK_SUITE_v4.2 · ACCESS GRANTED',
  headline: 'ANNUAL COLLEGIATE HACKATHON & INNOVATION SPRINT',
  weddingDate: 'October 24-26, 2026',
  weddingTime: 'Friday 5:00 PM – Sunday 3:00 PM',
  venueName: 'Gates Computer Science Building & Robotics Lab',
  venueAddress: '353 Jane Stanford Way',
  cityState: 'Stanford, CA 94305',
  mapsUrl: 'https://maps.google.com/?q=Gates+Computer+Science+Building+Stanford',
  rsvpDeadline: 'October 15, 2026',
  themeId: 'cyber-hackathon',
  timeline: [
    { id: 'h1', time: '5:00 PM (Fri)', title: 'Hacker Registration & Dinner', description: 'Check-in with QR badge, collect swag bags & WiFi credentials.', icon: 'cocktail' },
    { id: 'h2', time: '7:00 PM (Fri)', title: 'Opening Ceremony & Team Mixer', description: 'Keynote, API sponsor bounty reveals, and solo hacker matchmaking.', icon: 'ceremony' },
    { id: 'h3', time: '9:00 PM (Fri)', title: 'Hacking Begins (48H Clock Starts)', description: 'Mentors available in labs and on Discord.', icon: 'toast' },
    { id: 'h4', time: '12:00 AM (Sat)', title: 'Midnight Fuel & Pizza Drop', description: 'Red Bull, cold brews, fresh pizza, and Mario Kart tournament.', icon: 'dinner' },
    { id: 'h5', time: '12:00 PM (Sun)', title: 'Code Freeze & Devpost Submissions', description: 'Submit repos, video demos, and commit history.', icon: 'sparklers' },
    { id: 'h6', time: '2:00 PM (Sun)', title: 'Expo Showcase & $25K Award Ceremony', description: 'Live demos to judges, venture partners, and prize payouts.', icon: 'cake' }
  ],
  photos: [],
  hotels: [],
  dressCode: {
    title: 'Hacker Casual & Team Merch',
    subtitle: 'Hoodies, Sneakers & Laptops',
    description: 'Come as you are: hoodies, tees, comfortable sweatpants or jeans, and your favourite developer swag.',
    swatches: [
      { name: 'Terminal Obsidian', hex: '#0a0f1d' },
      { name: 'Cyber Cyan', hex: '#00ffcc' },
      { name: 'Electric Violet', hex: '#7928ca' },
      { name: 'Matrix Emerald', hex: '#00ff66' },
    ]
  },
  transportInfo: 'Free campus parking in Garage A. Shuttle available from Caltrain Station.',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=cyberpunk-2099-10701.mp3'
};

