import { ThemeConfig, ThemeId, WeddingData, RSVPRecord, MarketplaceOrder } from '../types/invitation';

export const THEME_PRESETS: Record<ThemeId, ThemeConfig> = {
  'olive-burgundy': {
    id: 'olive-burgundy',
    name: 'Olive & Burgundy Romance',
    subtitle: 'Classic vineyard botanical with deep burgundy wax seal and swan lake art',
    envelopeColor: '#535e3b',
    envelopeFlapColor: '#434d2f',
    waxSealBg: '#671928',
    waxSealBorder: '#8a2438',
    waxSealColor: '#f7e3c3',
    waxSealText: 'L&S',
    cardBg: '#2d3822',
    cardBorder: '#485737',
    cardTextPrimary: '#fbf8f2',
    cardTextSecondary: '#c8d4b8',
    cardAccentColor: '#d6a354',
    badgeBg: '#591421',
    badgeText: '#fcebe6',
    bgGradient: 'from-[#171c13] via-[#242c1e] to-[#12160f]',
    illustrationUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Claire de Lune (Acoustic Wedding Harp)',
  },
  'champagne-noir': {
    id: 'champagne-noir',
    name: 'Champagne & Noir Luxury',
    subtitle: 'Old money editorial chic with obsidian paper and shimmering champagne foil',
    envelopeColor: '#1c1c1c',
    envelopeFlapColor: '#141414',
    waxSealBg: '#b8964e',
    waxSealBorder: '#d4af37',
    waxSealColor: '#1c1c1c',
    waxSealText: 'V&A',
    cardBg: '#121212',
    cardBorder: '#383838',
    cardTextPrimary: '#fefefe',
    cardTextSecondary: '#d8caa7',
    cardAccentColor: '#d4af37',
    badgeBg: '#262626',
    badgeText: '#f3e8c9',
    bgGradient: 'from-[#0d0d0d] via-[#1a1a1a] to-[#0a0a0a]',
    illustrationUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'Canon in D (Strings & Piano)',
  },
  'tuscan-terracotta': {
    id: 'tuscan-terracotta',
    name: 'Tuscan Sun Terracotta',
    subtitle: 'Warm Italian countryside villa with burnt sienna, olive oil and travertine',
    envelopeColor: '#93543d',
    envelopeFlapColor: '#7a422e',
    waxSealBg: '#445136',
    waxSealBorder: '#5d6f4b',
    waxSealColor: '#faede3',
    waxSealText: 'M&E',
    cardBg: '#faf5ef',
    cardBorder: '#e4d5c4',
    cardTextPrimary: '#3f2b23',
    cardTextSecondary: '#7a5e51',
    cardAccentColor: '#93543d',
    badgeBg: '#80412b',
    badgeText: '#fff3eb',
    bgGradient: 'from-[#2e1d17] via-[#482e24] to-[#20130d]',
    illustrationUrl: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Italian Villa Romance (Acoustic Guitar)',
  },
  'dusty-rose': {
    id: 'dusty-rose',
    name: 'Dusty Rose & French Mauve',
    subtitle: 'Chateau garden romance with soft heirloom roses and delicate calligraphy',
    envelopeColor: '#7b5a63',
    envelopeFlapColor: '#63444c',
    waxSealBg: '#966e77',
    waxSealBorder: '#b38a94',
    waxSealColor: '#fff5f7',
    waxSealText: 'C&H',
    cardBg: '#fffbfb',
    cardBorder: '#eedbdc',
    cardTextPrimary: '#3e2a2f',
    cardTextSecondary: '#8a6b73',
    cardAccentColor: '#b06f80',
    badgeBg: '#6b4851',
    badgeText: '#fff0f3',
    bgGradient: 'from-[#26171b] via-[#3a252b] to-[#1c1114]',
    illustrationUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=wedding-grand-piano-123719.mp3',
    musicTitle: 'A Thousand Years (Violin Duo)',
  },
  'botanical-emerald': {
    id: 'botanical-emerald',
    name: 'Imperial Emerald & Gold',
    subtitle: 'Lush conservatory greenery, gold leaf typography, and crisp linen cards',
    envelopeColor: '#1c4436',
    envelopeFlapColor: '#133328',
    waxSealBg: '#c29b38',
    waxSealBorder: '#dfb755',
    waxSealColor: '#133328',
    waxSealText: 'G&T',
    cardBg: '#fbfcf9',
    cardBorder: '#d6e2db',
    cardTextPrimary: '#163127',
    cardTextSecondary: '#476558',
    cardAccentColor: '#b8860b',
    badgeBg: '#1b4436',
    badgeText: '#f0fdf4',
    bgGradient: 'from-[#081813] via-[#0f2a20] to-[#05100c]',
    illustrationUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80',
    musicTrackUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
    musicTitle: 'Bridal Chorus (Cello & Harp)',
  },
};

export const INITIAL_WEDDING_DATA: WeddingData = {
  id: 'wed-001',
  slug: 'liam-and-scarlett',
  coupleName1: 'Liam',
  coupleName2: 'Scarlett',
  coupleInitials: 'L&S',
  subtitleIntro: 'INTRODUCING',
  headline: 'PLEASE JOIN US FOR THE WEDDING OF',
  weddingDate: '2027-08-11',
  weddingTime: '3:45 PM',
  venueName: 'Cable Bay Vineyard',
  venueAddress: '12 Nick Johnstone Drive, Oneroa',
  cityState: 'Waiheke Island, New Zealand',
  mapsUrl: 'https://maps.google.com/?q=Cable+Bay+Vineyard+Waiheke+Island',
  rsvpDeadline: 'June 15, 2027',
  themeId: 'olive-burgundy',
  transportInfo: 'On the day, return transport will be arranged from central Oneroa and the ferry wharf to Cable Bay Vineyard and back after the reception.',
  giftRegistryUrl: 'https://www.zola.com/registry',
  musicEnabled: true,
  backgroundMusicUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3',
  timeline: [
    {
      id: 't-1',
      time: '3:45 PM',
      title: 'Guest Arrival & Champagne Welcome',
      description: 'Guests arrive at the glasshouse terrace for sparkling wine and live acoustic harp.',
      icon: 'cocktail',
    },
    {
      id: 't-2',
      time: '4:15 PM',
      title: 'The Wedding Ceremony',
      description: 'Exchange of vows overlooking the panoramic bay vineyards.',
      icon: 'ceremony',
    },
    {
      id: 't-3',
      time: '5:00 PM',
      title: 'Cocktails & Canapes',
      description: 'Sunset drinks, gourmet oyster bar, and lawn games in the olive grove.',
      icon: 'cocktail',
    },
    {
      id: 't-4',
      time: '7:00 PM',
      title: 'Seated Dinner & Speeches',
      description: 'Five-course farm-to-table wine pairing dinner followed by champagne toasts.',
      icon: 'toast',
    },
    {
      id: 't-5',
      time: '8:30 PM',
      title: 'Cutting the Wedding Cake',
      description: 'Sweet moments, espresso bar, and artisan dessert table.',
      icon: 'cake',
    },
    {
      id: 't-6',
      time: '9:00 PM - Midnight',
      title: 'First Dance & Dancing Time',
      description: 'Live 7-piece band and open cocktail bar to dance the night away.',
      icon: 'dancing',
    },
  ],
  hotels: [
    {
      id: 'h-1',
      name: 'Oneroa Bay Luxury Retreat',
      badge: '5 Min from Venue',
      description: 'Boutique waterfront villas with private infinity pools and coastal views.',
      bookingUrl: 'https://www.booking.com',
      discountCode: 'LIAMSCARLETT27',
      priceLevel: '$$$$',
    },
    {
      id: 'h-2',
      name: 'The Vineyard Estate Cottages',
      badge: 'On-site Partner',
      description: 'Charming rustic stone suites nestled right among the vines with breakfast included.',
      bookingUrl: 'https://www.airbnb.com',
      discountCode: 'WEDDINGGUEST',
      priceLevel: '$$$',
    },
  ],
  dressCode: {
    title: 'Dress to Impress',
    subtitle: 'Black Tie Optional / Vineyard Elegance',
    description: "We would love for you to join us celebrating in style in formal vineyard attire. For the ladies, floor-length or elevated midi dresses in rich tones. For gentlemen, dark suits or classic tuxedos.",
    swatches: [
      { name: 'Olive Green', hex: '#4e5b30' },
      { name: 'Deep Burgundy', hex: '#671928' },
      { name: 'Warm Terracotta', hex: '#93543d' },
      { name: 'Champagne Gold', hex: '#d4af37' },
      { name: 'Black Tie Noir', hex: '#1c1c1c' },
    ],
  },
  photos: [
    {
      id: 'p-1',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
      caption: 'Where it all started - Paris, 2021',
      dateTag: 'October 2021',
    },
    {
      id: 'p-2',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
      caption: 'She said YES on the Amalfi Coast!',
      dateTag: 'September 2024',
    },
    {
      id: 'p-3',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
      caption: 'Counting down the days with you',
      dateTag: 'Summer 2026',
    },
  ],
};

export const INITIAL_RSVPS: RSVPRecord[] = [
  {
    id: 'rsvp-1',
    weddingId: 'wed-001',
    guestName: 'Eleanor Vance',
    guestEmail: 'eleanor.vance@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Julian Vance'],
    mealChoice: 'Charred Prime Beef Tenderloin',
    dietaryNotes: 'Gluten-free for Eleanor',
    songRequest: 'At Last - Etta James',
    personalMessage: 'So incredibly thrilled for you both! Can not wait to celebrate under the stars!',
    submittedAt: '2026-08-14T10:30:00Z',
  },
  {
    id: 'rsvp-2',
    weddingId: 'wed-001',
    guestName: 'Marcus Sterling',
    guestEmail: 'marcus.s@example.com',
    attendance: 'attending',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'Crispy Skin King Salmon',
    dietaryNotes: 'None',
    songRequest: 'September - Earth, Wind & Fire',
    personalMessage: 'Ready for the greatest party of 2027!',
    submittedAt: '2026-08-15T14:12:00Z',
  },
  {
    id: 'rsvp-3',
    weddingId: 'wed-001',
    guestName: 'Sophia Montgomery',
    guestEmail: 'sophia.m@example.com',
    attendance: 'attending',
    partySize: 2,
    plusOneNames: ['Lucas Montgomery'],
    mealChoice: 'Wild Mushroom & Truffle Risotto (V)',
    dietaryNotes: 'Vegetarian',
    songRequest: 'Lover - Taylor Swift',
    personalMessage: 'Liam & Scarlett, you two are pure magic. See you on Waiheke!',
    submittedAt: '2026-08-16T09:45:00Z',
  },
  {
    id: 'rsvp-4',
    weddingId: 'wed-001',
    guestName: 'Arthur Pendelton',
    guestEmail: 'arthur.p@example.com',
    attendance: 'declined',
    partySize: 1,
    plusOneNames: [],
    mealChoice: 'N/A',
    dietaryNotes: '',
    personalMessage: 'Sending all our love from London! Sadly cannot make the flight but will be toasting with champagne!',
    submittedAt: '2026-08-16T16:20:00Z',
  },
];

export const INITIAL_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ord-8891',
    claimCode: 'ETSY-OLIVE-9482',
    platform: 'Etsy',
    buyerName: 'Charlotte Miller',
    buyerEmail: 'charlotte.m@gmail.com',
    themeSelected: 'olive-burgundy',
    orderStatus: 'claimed',
    createdAt: '2026-09-08 19:30',
    claimedAt: '2026-09-08 20:15',
  },
  {
    id: 'ord-8892',
    claimCode: 'GUM-CHAMP-1029',
    platform: 'Gumroad',
    buyerName: 'Benjamin Hayes',
    buyerEmail: 'ben.hayes@outlook.com',
    themeSelected: 'champagne-noir',
    orderStatus: 'generated',
    createdAt: '2026-09-09 08:45',
  },
  {
    id: 'ord-8893',
    claimCode: 'ETSY-TUSCAN-7734',
    platform: 'Etsy',
    buyerName: 'Isabella Rossi',
    buyerEmail: 'isabella.r@gmail.com',
    themeSelected: 'tuscan-terracotta',
    orderStatus: 'published',
    createdAt: '2026-09-07 14:10',
    claimedAt: '2026-09-07 15:00',
  }
];
